#!/usr/bin/env bash
# Commands to install Nginx on Web-Sever-01

# Installing
sudo apt-get update
sudo apt-get -y install nginx

# Firewall
sudo ufw allow 'Nginx HTTP'

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations for Syntax errors
sudo nginx -t

# Restarting Nginx
sudo service nginx start


